language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
before_install:
  - sudo add-apt-repository ppa:ultrafredde/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq task
  - task --version
install: python setup.py install
script: python setup.py test
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: always
