sudo: required
dist: trusty
language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
env:
 - TASKWARRIOR=v2.2.0
 - TASKWARRIOR=v2.3.0
 - TASKWARRIOR=v2.4.0
 - TASKWARRIOR=v2.4.1
 - TASKWARRIOR=v2.4.2
 - TASKWARRIOR=v2.4.3
 - TASKWARRIOR=v2.4.4
 - TASKWARRIOR=v2.5.0
 - TASKWARRIOR=v2.5.1
before_install:
  - sudo apt-get install -y python-dev cmake build-essential libgnutls28-dev uuid-dev gnutls-bin chrpath libssl-dev libfontconfig1-dev
  - git clone https://git.tasktools.org/scm/tm/task.git
  - cd task
  - git checkout $TASKWARRIOR
  - cmake .
  - make
  - sudo make install
  - task --version
  - cd ../
install: python setup.py install
script: python setup.py test
notifications:
    email: true
    irc:
        - "irc.freenode.net#threebean"
    on_success: change
    on_failure: always
